config/routes.rb
Rails.application.routes.draw do

  get 'perusal/new'
  get 'perusal/show'
  get 'frame/create'
  resources :location do
  end

  resources :hive do
  end

  resources :super do
  end

  resources :frame do
  end

  resources :perusal do
  end

  #get 'location/new'
  devise_for :users, controllers: { sessions: 'users/sessions',
                                              registrations: 'users/registrations',
                                              passwords: 'users/passwords'}

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/frame.rb
class Frame < ApplicationRecord
  belongs_to :super

  validates :letter, presence: :true, length: { maximum: 1 }
end

app/models/hive.rb
class Hive < ApplicationRecord
  belongs_to :location

  validates :hive_number, presence: :true
  has_many :supers
  has_many :perusals
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user

  validates :name, presence: :true

  has_many :hives
end

app/models/perusal.rb
class Perusal < ApplicationRecord
  belongs_to :hive
end

app/models/super.rb
class Super < ApplicationRecord
  belongs_to :hive

  has_many :frames
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: [:login]

  validates :username, presence: :true, uniqueness: { case_sensitive: false }, length: { minimum: 3 }
  validate :validate_username

  has_many :locations

  attr_writer :login

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/frame_controller.rb
class FrameController < ApplicationController
  def create
    @frame = Frame.new(frame_params)
    @super = Super.find(@frame.super_id)

    if @frame.save
      redirect_to hive_path(@super.hive_id)
    else
      flash.alert = "Wrong data!"
    end
  end

  def edit
    @frame = Frame.find(params[:id])
  end

  def update
    @frame = Frame.find(params[:id])
    @super = Super.find(@frame.super_id)

    if @frame.update(params.require(:frame).permit(:letter, :frame_type, :super_id))
      flash[:success] = "Status changed"
      redirect_to hive_path(@super.hive_id)
    else
      flash[:danger] = "There was a problem changing the status"
    end
  end

  def destroy
    @frame = Frame.find(params[:id])
    @super = Super.find(@frame.super_id)

    @frame.destroy
    redirect_to hive_path(@super.hive_id)
  end

  private
  def frame_params
    params.permit(:letter, :frame_type, :super_id)
  end
end

app/controllers/hive_controller.rb
class HiveController < ApplicationController
  def index
    @locations = Location.all
  end

  def show
    @hive = Hive.find(params[:id])
    @location = Location.find(@hive.location_id)
    @supers = Super.where(hive_id: @hive.id)
    @supers = @supers.sort_by { |sup |sup.number  }
    @frames = Frame.where(super_id: Super.where(hive_id: @hive.id).ids)
    @frames = @frames.sort_by { |frm |frm.letter  }
  end

  def create

    @hive = Hive.new(hive_params)

    if @hive.save
      redirect_to location_path(@hive.location_id)
    else
      flash.alert = "Wrong data!"
    end

  end

  private
  def hive_params
    params.permit(:hive_number, :colony_type, :year_color, :colony_created_at, :queen_added_at, :breed, :hive_type, :location_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @locations = Location.all
  end
end

app/controllers/location_controller.rb
class LocationController < ApplicationController

  def index
    @locations = Location.all
  end

  def show
    @location = Location.find(params[:id])
    @locations = Location.all
    @hives = Hive.where(location_id: @location.id)
    @hives = @hives.sort_by { |hive |hive.hive_number  }
  end

  def edit
    @location = Location.find(params[:id])
  end

  def create
    if params[:latitude] != "" && params[:longitude] != ""
      if params[:country] != "" && params[:state] != ""
        @location = Location.new(location_params)
      else
        @location = Location.new(location_coordinates_params)
      end
    else if params[:country] && params[:state] && params[:zip_code] && params[:city] && params[:street] && params[:street_number]
           @location = Location.new(location_address_params)
         else
           flash["Location not Valid"]
         end
    end

    @location.user_id = current_user.id


    if @location.save
      redirect_to @location
    else
      flash.alert = "Wrong data!"
    end

  end

  def update
    @location = Location.find(params[:id])

    if @location.user_id == current_user.id
      if @location.update(location_params)
        redirect_to @location
      else
        render 'edit'
      end
    end
  end

  def destroy
    @location = Location.find(params[:id])
    if @location.user_id == current_user.id
      @location.destroy
      redirect_to location_path
    else
      flash[:danger] = "You are not allowed to delete this article!"
    end
  end

  private
  def location_params
    params.permit(:name, :country, :state, :zip_code, :city, :street, :street_number, :latitude, :longitude)
  end
  def location_address_params
    params.permit(:name, :country, :state, :zip_code, :city, :street, :street_number)
  end
  def location_coordinates_params
    params.permit(:name, :latitude, :longitude)
  end
end

app/controllers/perusal_controller.rb
class PerusalController < ApplicationController
  def new
    @hive = Hive.find(params[:hive_id])
  end

  def show
    @hive = Hive.find(params[:hive_id])
    @perusals = Perusal.where(hive_id: @hive.id)
    @perusals = @perusals.sort_by { |per |per.perusal_date }.reverse
  end

  def create

    @perusal = Perusal.new(perusal_params)

    if @perusal.save
      redirect_to hive_path(@perusal.hive_id)
    else
      flash.alert = "Wrong data!"
    end

  end

  private
  def perusal_params
    params.permit(:population_size, :honeycomb_seat, :gentleness, :brood, :bees, :drone_brood_cutted, :queen_seen, :hive_weight, :remark, :perusal_date, :hive_id)
  end
end

app/controllers/super_controller.rb
class SuperController < ApplicationController

  def create

    @super = Super.new(super_params)

    if @super.save
      redirect_to hive_path(@super.hive_id)
    else
      flash.alert = "Wrong data!"
    end

  end

  private
  def super_params
    params.permit(:number, :super_type, :hive_id)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/frame_helper.rb
module FrameHelper
end

app/helpers/hive_helper.rb
module HiveHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/perusal_helper.rb
module PerusalHelper
end

app/helpers/super_helper.rb
module SuperHelper
end

app/views/frame/_edit.html.erb
<%= javascript_include_tag "frame", "data-turbolinks-track" => true  %>

<div class="edit_frame" >

  <% @edit_frame_form = "edit_frame_form_" + @super_index.to_s + "_" + @frame_index.to_s %>
  <% @close_edit_frame = "close_edit_frame_" + @super_index.to_s + "_" + @frame_index.to_s %>
  <% @edit_frame_heading = "edit_frame_heading_" + @super_index.to_s%>
  <% @hidden_super_id = "hidden_super_id_" + @super_index.to_s%>

  <div id="<%= @edit_frame_form %>" class="hide hidden edit_frame_form">

    <%= form_with model: @frame_exist, url: '/frame/'+@frame_exist.id.to_s, class: 'transparent', local: true do |f| %>

      <div class="form_edit_frame">
        <h1 class="h3 mb-3 font-weight-normal" style="color: #f2d002">
          <div style="display: inline; text-decoration: underline;">Edit Frame</div>
          <div style="display: inline;"><i class="fa fa-pencil"> </i></div>
        </h1>

        <div class="form-row" style="margin-top: -8px">
          <div class="col-1">
            <i class="fa fa-times-circle fa-lg close_edit_frame" id="<%= @close_edit_frame %>" style="color: #777; margin-top: 10px; margin-left: 6px"></i>
          </div>
          <div class="col" style="max-width: 80px">
            <%= f.text_field :letter, class: 'form-control', placeholder: 'Letter', type: 'text', autofocus: true, id: 'letter' + @frame_exist.id.to_s, value: @frame_exist.letter.to_s, style: 'background-color: transparent; border-color: #f2d002; color: #f2d002'%>
          </div>
          <div class="col">
            <%= f.select :frame_type, options_for_select({"Middle Wall" => "0", "Honey" => "1", "Pollen" => "2", "Feed" => "3", "Brood" => "4", "Drone" => "5", "Empty" => "6"}, :selected => @frame_exist.frame_type), class: 'form-control', id: 'select_frame_type' %>
          </div>

          <%= f.hidden_field :super_id, id: @super_id %>

          <div class="col" style="max-width: 80px; margin-left: -8px">
            <div class="actions">
              <%= f.submit "Edit", class: 'btn', type: 'submit', id: 'edit-frame-submit', style: ' border: 1px #f2d002 solid'%>
            </div>
          </div>
        </div>

      </div>

    <% end %>

  </div>

</div>

app/views/frame/_new.html.erb
<%= javascript_include_tag "frame", "data-turbolinks-track" => true  %>

<div class="new_frame">

  <% @new_frame_form = "new_frame_form_" + @super_index.to_s%>
  <% @close_add_frame = "close_add_frame_" + @super_index.to_s%>
  <% @new_frame_heading = "new_frame_heading_" + @super_index.to_s%>
  <% @hidden_super_id = "hidden_super_id_" + @super_index.to_s%>
  <% @img_id = "img_new_frame_" + @super_index.to_s%>
  <%= image_tag 'framev1.png', id: @img_id, class: 'img_new_frame' %>

  <div id="<%= @new_frame_heading %>" class="show shown new_frame_heading">
    <i class="fa fa-plus-circle fa-2x"></i>
  </div>

  <div id="<%= @new_frame_form %>" class="hide hidden new_frame_form">

    <%= form_with model: @frame, url: '/frame', class: 'transparent', local: true do |f| %>

      <div class="form_add_frame">
        <h1 class="h3 mb-3 font-weight-normal" style="color: #f2d002">
          <div style="display: inline; text-decoration: underline;">Add Frame</div>
          <div style="display: inline; font-size: 22px"><i class="fa fa-plus-circle"> </i></div>
        </h1>

        <div class="form-row" style="margin-top: -8px">
          <div class="col-1">
            <i class="fa fa-times-circle fa-lg close_add_frame" id="<%= @close_add_frame %>" style="color: #777; margin-top: 10px; margin-left: 6px"></i>
          </div>
          <div class="col" style="max-width: 80px">
            <%= f.text_field :letter, class: 'form-control', placeholder: 'Letter', type: 'text', autofocus: true, style: 'background-color: transparent; border-color: #f2d002; color: #f2d002'%>
          </div>
          <div class="col">
            <%= f.select :frame_type, options_for_select({"Middle Wall" => "0", "Honey" => "1", "Pollen" => "2", "Feed" => "3", "Brood" => "4", "Drone" => "5", "Empty" => "6"}, "6"), class: 'form-control', id: 'select_frame_type' %>
          </div>

          <%= f.hidden_field :super_id, id: @hidden_super_id %>

          <div class="col" style="max-width: 80px; margin-left: -8px">
            <div class="actions">
              <%= f.submit "Add", class: 'btn', type: 'submit', id: 'add-frame-submit', style: ' border: 1px #f2d002 solid'%>
            </div>
          </div>
        </div>

      </div>

    <% end %>
  </div>

</div>

app/views/frame/edit.html.erb
<h3>Edit it: <%= @frame.id %></h3>

app/views/hive/_new.html.erb
<div id="new_hive_comp" style="margin-bottom: 100px">

<%= image_tag 'big_honeycomb_centered.png', id: 'img_new_hive'%>
  <div id="new_hive_heading" class="show shown">
    <h3> New </h3>
    <h3> Hive </h3>
    <%= image_tag 'hive/hive.png', id: 'img_hive', style: 'zoom: 13%; margin-top: -5px; margin-bottom: 100px;'%>
    <i class="fa fa-plus-circle fa-xs"></i>
  </div>

  <div id="new_hive_form" class="hide hidden transparent">

    <div style="margin-bottom: 20px">
      <i class="fa fa-times-circle fa-lg" id="close_add_hive_form"></i>
    </div>

    <%= form_with model: @hive, :url => '/hive',class: 'transparent', local: true do |f| %>

      <div class="form-add-hive">
        <h1 class="h3 mb-3 font-weight-normal" style="text-decoration: underline">New Hive</h1>

        <div class="form-row" style="margin-bottom: 10px">
          <div class="col-2"></div>
          <div class="col">
            <div class="input-group">
              <div class="input-group-prepend" style="width: 80px">
                <%= f.text_field :hive_number, autofocus: true, class: 'form-control', placeholder: 'Nr.', type: 'text', style: 'text-align: center; margin-right: 10px'%>
              </div>
              <%= f.select :location_id, options_for_select(@locations.map{ |l| [l.name, l.id] }, :selected => @location.id), class: 'form-control' %>
            </div>
          </div>
          <div class="col-2"></div>
        </div>

        <div class="form-row">
          <%= f.text_field :colony_type, class: 'form-control top', placeholder: 'Colony type', type: 'text' %>
        </div>

        <div class="form-row">
          <%= f.text_field :hive_type, class: 'form-control middle', placeholder: 'Hive type', type: 'text' %>
        </div>

        <div class="form-row">
          <div class="input-group">
            <div class="input-group-prepend">
              <span id="date_span" class="input-group-text middle" style="width: 160px;">Colony created at:</span>
            </div>
            <%= f.date_field :colony_created_at, class: 'form-control middle', placeholder: 'Colony created at', type: 'date' %>
          </div>
        </div>

        <div class="form-row">
          <div class="input-group">
            <div class="input-group-prepend">
              <span id="date_span" class="input-group-text bottom" style="width: 160px">Queen added at:</span>
            </div>
            <%= f.date_field :queen_added_at, class: 'form-control bottom', placeholder: 'Queen added at', type: 'date' %>
          </div>
        </div>

        <div id="additional_settings_input_form" class="hidden" style="margin-bottom: -5px">
          <div class="form-row" style="margin-top: 10px">
            <div>
              <%= f.text_field :breed, class: 'form-control', placeholder: 'Breed', type: 'text' %>
            </div>
            <div class="col">
              <div style="border: 1px #f2d002 solid; border-radius: 4px; height: 38px; width: 207px">
                <div class="dropdown">
                  <button class="btn _select_color dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: #f2d002">Select year color</button>
                  <ul class="dropdown-menu _select_color_drop" aria-labelledby="dropdownMenu1">
                    <li><span data-text-display="White"  data-value=0 class="color white"></span></li>
                    <li><span data-text-display="Yellow" data-value=1 class="color yellow"></span></li>
                    <li><span data-text-display="Red"    data-value=2 class="color red"></span></li>
                    <li><span data-text-display="Green"  data-value=3 class="color green"></span></li>
                    <li><span data-text-display="Blue"   data-value=4 class="color blue"></span></li>
                  </ul>
                </div>
                <%= f.hidden_field :year_color%>
              </div>
            </div>
          </div>
        </div>

        <div class="form-row", style="margin-top: 10px; margin-bottom: 10px">
          <div class="form-row" id="slider_row" style="color: #777; align: center">
            <label class="switch" style="margin-bottom: 20px; margin-top: -5px">
              <input type="checkbox" id="activate_additional_settings_input">
              <span class="slider"></span>
            </label>
            Show additional settings
          </div>
        </div>

        <div class="form-row">
          <div class="col-3"></div>
          <div class="col">
            <div class="actions">
             <%= f.submit "Add Hive", class: 'btn', type: 'submit', id: 'add-hive-submit'%>
           </div>
          </div>
          <div class="col-3"></div>
        </div>

      </div>

    <% end %>
  </div>

</div>

app/views/hive/_new_perusal_comb.html.erb
<div id="new_perusal_comb" style="float: right; color: #f2d002; position: relative; z-index: 20">
  <%= image_tag 'big_honeycomb_centered.png', style: 'width: 240px; height: 240px'%>
  <h2 style="margin-top: -160px" onclick="location.href= '<%= perusal_new_path(:hive_id => @hive.id) %>'" >
    New Perusal<br>
    <i class="fa fa-search-plus fa-2x" ></i>
  </h2>
</div>

app/views/hive/_show_all_perusal_comb.html.erb
<div id="show_all_perusal_comb" style="float: left; color: #f2d002; position: relative; z-index: 20; margin-left: -59px">
  <%= image_tag 'big_honeycomb_centered.png', style: 'width: 240px; height: 240px'%>
  <h2 style="margin-top: -160px" onclick="location.href= '<%= perusal_show_path(:hive_id => @hive.id) %>'" >
    All Perusals<br>
    <i class="fa fa-search fa-2x" ></i>
  </h2>
</div>

app/views/hive/_show_hive_comb.html.erb
<div id="show_hive_comb">

  <%= image_tag 'big_honeycomb_centered.png', id: 'img_show_hive', style: 'margin-left: -66px'%>

  <div id="show_hive_table" class="transparent hidden hide">

    <i class="fa fa-times-circle fa-lg" id="close_show_comb"></i>

    <div id="hive_number_zoomed">
      <h1 class="h3 mb-3 font-weight-normal" style="margin-top: 10px; text-decoration: underline;"><%= @hive.hive_number %></h1>
      <h2 class="h3 mb-3 font-weight-normal" style="font-size: 24px; margin-top: -10px">Location: <%= @location.name %></h2>
    </div>

    <table class="separate" id="show_table_hive">

      <% if @hive.colony_type != "" %>
        <tr>
          <td class="long_td">Colony Type:</td>
          <td colspan="3"><%= @hive.colony_type %></td>
        </tr>
      <% end %>

      <% if @hive.hive_type != "" %>
        <tr>
          <td class="long_td">Hive Type:</td>
          <td colspan="3"><%= @hive.hive_type %></td>
        </tr>
      <% end %>

      <% if @hive.colony_created_at != nil %>
        <tr>
          <td class="long_td">Colony created at:</td>
          <td colspan="3"><%= @hive.colony_created_at %></td>
        </tr>
      <% end %>

      <% if @hive.queen_added_at != nil %>
        <tr>
          <td class="long_td">Queen added at:</td>
          <td colspan="3"><%= @hive.queen_added_at %></td>
        </tr>
      <% end %>

      <% if @hive.breed != "" || @hive.year_color %>
        <tr>
          <td class="long_td">Breed:</td>
          <td class="normal_td"><%= @hive.breed %></td>
          <td class="normal_td">Year color:</td>
          <td>
            <% if @hive.year_color %>
              <% case @hive.year_color %>
              <% when 0 %>
                <span class="color white"></span>
              <% when 1 %>
                <span class="color yellow"></span>
              <% when 2 %>
                <span class="color red"></span>
              <% when 3 %>
                <span class="color green"></span>
              <% when 4 %>
                <span class="color blue"></span>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>

    </table>

  </div>

  <div id="hive_number_unzoomed">
    <h1 class="h3 mb-3 font-weight-normal show"><%= @hive.hive_number %></h1>
    <% if @hive.year_color %>
      <% case @hive.year_color %>
    <% when 0 %>
        <%= image_tag 'hive/hive_white.png', id: 'img_hive', style: 'zoom: 30%; margin-top: -5px; margin-bottom: 100px;'%>
      <% when 1 %>
        <%= image_tag 'hive/hive_yellow.png', id: 'img_hive', style: 'zoom: 30%; margin-top: -5px; margin-bottom: 100px;'%>
      <% when 2 %>
        <%= image_tag 'hive/hive_red.png', id: 'img_hive', style: 'zoom: 30%; margin-top: -5px; margin-bottom: 100px;'%>
      <% when 3 %>
        <%= image_tag 'hive/hive_green.png', id: 'img_hive', style: 'zoom: 30%; margin-top: -5px; margin-bottom: 100px;'%>
      <% when 4 %>
        <%= image_tag 'hive/hive_blue.png', id: 'img_hive', style: 'zoom: 30%; margin-top: -5px; margin-bottom: 100px;'%>
      <% end %>
    <% else %>
      <%= image_tag 'hive/hive.png', id: 'img_hive', style: 'zoom: 30%; margin-top: -5px; margin-bottom: 100px;'%>
    <% end %>
  </div>

</div>

app/views/hive/index.html.erb
<%= javascript_include_tag "hive", "data-turbolinks-track" => true  %>

<div class="wrapper">

  <%= render 'nav' %>

  <div style="height: 300px"></div>

  <div style="text-align: center">
    <%= render 'new' %>
  </div>

</div>

app/views/hive/show.html.erb
<%= javascript_include_tag "hive", "data-turbolinks-track" => true  %>

<div class="wrapper">

  <%= render 'nav' %>

  <div style="height: 190px"></div>


  <div style="text-align: center">

    <div class="row">
      <div class="col" style="padding: 0; margin-left: 60px; margin-top: 102px">
        <%= render 'new_perusal_comb' %>
      </div>
      <div class="col" id="col_show_hive_comb" style="max-width: 106px; padding: 0">
        <%= render 'show_hive_comb' %>
      </div>
      <div class="col" style="padding: 0; margin-left: 60px; margin-top: 102px">
        <%= render :partial => 'show_all_perusal_comb' %>
      </div>
    </div>

    <br><br><br>

    <%= render 'super/new' %>

    <br><br><br>

    <%= render 'super/all_supers' %>

  </div>

</div>

app/views/location/_hives_table.html.erb
<div class="row">
  <div class="col"></div>

  <div class="col">
    <table id="hives_table">
      <% @hives.each_with_index do |hive, index| %>
        <% if index%10 == 0 %>
          <tr>
        <% end %>
        <td onclick="location.href= '<%= hive_path(hive.id) %>'" class="hive_comp" style="padding: 0;">
          <%= image_tag 'big_honeycomb_centered.png', style: 'zoom: 13%; margin: 20px; margin-top: 0 !important;'%>
          <div style="margin-top: -96px;">
            <h5 style="color: #f2d002"><%= hive.hive_number %></h5>
            <% if hive.year_color %>
              <% case hive.year_color %>
                <% when 0 %>
                  <%= image_tag 'hive/hive_white.png', id: 'img_hive', style: 'zoom: 20%; margin-top: -5px; margin-bottom: 100px;'%>
                <% when 1 %>
                  <%= image_tag 'hive/hive_yellow.png', id: 'img_hive', style: 'zoom: 20%; margin-top: -5px; margin-bottom: 100px;'%>
                <% when 2 %>
                  <%= image_tag 'hive/hive_red.png', id: 'img_hive', style: 'zoom: 20%; margin-top: -5px; margin-bottom: 100px;'%>
                <% when 3 %>
                  <%= image_tag 'hive/hive_green.png', id: 'img_hive', style: 'zoom: 20%; margin-top: -5px; margin-bottom: 100px;'%>
                <% when 4 %>
                  <%= image_tag 'hive/hive_blue.png', id: 'img_hive', style: 'zoom: 20%; margin-top: -5px; margin-bottom: 100px;'%>
              <% end %>
            <% else %>
              <%= image_tag 'hive/hive.png', id: 'img_hive', style: 'zoom: 20%; margin-top: -5px; margin-bottom: 100px;'%>
            <% end %>
          </div>
        </td>
        <% if index%10 == 9 %>
          </tr>
        <% end %>
      <% end %>
    </table>
  </div>

  <div class="col"></div>
</div>

app/views/location/_show_all.html.erb
<div id="show_all_location_comp">

  <%= image_tag 'big_honeycomb_centered.png', id: 'img_show_all_location'%>
  <div id="show_all_location_heading" class="show shown">
    <h3> Show all </h3>
    <h3> Locations </h3>
    <i class="fa fa-eye fa-2x"></i>
  </div>


  <div class="hide hidden" id="show_all_location_table" style="align: center">
    <div style="margin-bottom: 20px">
      <i class="fa fa-times-circle fa-lg" id="close_show_all_table"></i>
    </div>

    <table class="separate" id="show_all_table" style="margin-top: -30px;">

      <% @address_table_shown = false %>

      <% @locations.each do |location| %>
        <% if location.country && location.state %>
          <% @address_table_shown = true %>
        <% end %>
      <% end %>

      <% if @address_table_shown %>
        <tr class="top" id="show_all_location_table_th">
          <th>Name</th>
          <th>Country</th>
          <th>State</th>
        </tr>
      <% end %>

      <% @locations.each do |location| %>

        <% if location.country && location.state %>
          <tr onclick="location.href= '<%= location_path(location.id) %>'" class="location_table_cell reset_all">
            <td><%= location.name %></td>
            <td><%= location.country %></td>
            <td><%= location.state %></td>
          </tr>
        <% end %>

      <% end %>

      <% @coordinates_table_shown = false %>

      <% @locations.each do |location| %>
        <% if (location.latitude && location.longitude) && (!location.country && !location.state)%>
          <% @coordinates_table_shown = true %>
        <% end %>
      <% end %>

      <% if @coordinates_table_shown %>
        <tr class="top" id="show_all_location_table_th">
          <th>Name</th>
          <th>Latitude</th>
          <th>Longitude</th>
        </tr>
      <% end %>

      <% @locations.each do |location| %>

        <% if (location.latitude && location.longitude) && (!location.country && !location.state)%>
          <tr onclick="location.href= '<%= location_path(location.id) %>'" class="location_table_cell reset_all">
            <td><%= location.name %></td>
            <td><%= location.latitude %></td>
            <td><%= location.longitude %></td>
          </tr>
        <% end %>

      <% end %>

    </table>

  </div>

</div>

app/views/location/index.html.erb
<%= javascript_include_tag "location", "data-turbolinks-track" => true  %>

<div class="wrapper">

  <%= render 'nav' %>

  <div style="height: 300px"></div>

  <div style="text-align: center">
    <%= render 'new' %>
    <%= render 'show_all' %>
  </div>

</div>

app/views/location/show.html.erb
<%= javascript_include_tag "location", "data-turbolinks-track" => true  %>
<%= javascript_include_tag "hive", "data-turbolinks-track" => true  %>

<div class="wrapper">

  <%= render 'nav' %>

  <div style="height: 190px"></div>

  <div style="text-align: center">
    <%= render 'show_location_comb' %>

    <div style="margin-top: 100px; align: center">
      <%= render 'hive/new' %>
    </div>

    <%= render 'hives_table' %>

  </div>

</div>